from __future__ import annotations

from .models import TaskNode


def build_ielts_task_graph() -> list[TaskNode]:
    exam = "IELTS"
    return [
        TaskNode(
            "foundation_sentence_structure",
            "Basic sentence structure",
            "foundation",
            45,
            42,
            2,
            exam=exam,
            resource_query="IELTS basic sentence structure grammar explanation and drills",
        ),
        TaskNode(
            "foundation_complex_sentences",
            "Complex sentence patterns",
            "foundation",
            50,
            48,
            3,
            ["foundation_sentence_structure"],
            exam=exam,
            resource_query="IELTS complex sentence patterns grammar practice",
        ),
        TaskNode(
            "foundation_academic_vocab",
            "Vocabulary building for academic topics",
            "foundation",
            40,
            44,
            2,
            exam=exam,
            resource_query="IELTS academic vocabulary topic based study set",
        ),
        TaskNode(
            "writing_task2_structure",
            "Task 2 essay structure",
            "writing",
            55,
            72,
            3,
            ["foundation_sentence_structure"],
            exam=exam,
            resource_query="IELTS Writing Task 2 essay structure band 7 explanation and practice",
        ),
        TaskNode(
            "writing_paragraph_development",
            "Paragraph development",
            "writing",
            50,
            68,
            3,
            ["writing_task2_structure", "foundation_complex_sentences"],
            exam=exam,
            resource_query="IELTS Writing Task 2 paragraph development examples practice",
        ),
        TaskNode(
            "writing_argument_evidence",
            "Argument examples and evidence",
            "writing",
            45,
            64,
            3,
            ["writing_task2_structure", "foundation_academic_vocab"],
            exam=exam,
            resource_query="IELTS Task 2 argument evidence examples practice",
        ),
        TaskNode(
            "writing_timed_task2",
            "Timed Task 2 practice",
            "writing",
            60,
            86,
            4,
            ["writing_paragraph_development", "writing_argument_evidence"],
            exam=exam,
            resource_query="IELTS Writing Task 2 timed practice feedback rubric",
        ),
        TaskNode(
            "reading_skimming_scanning",
            "Skimming and scanning",
            "reading",
            40,
            54,
            2,
            exam=exam,
            resource_query="IELTS Reading skimming scanning techniques practice",
        ),
        TaskNode(
            "reading_matching_headings",
            "Matching headings",
            "reading",
            45,
            63,
            3,
            ["reading_skimming_scanning"],
            exam=exam,
            resource_query="IELTS Reading matching headings strategy practice",
        ),
        TaskNode(
            "reading_tfn",
            "True / False / Not Given practice",
            "reading",
            45,
            66,
            3,
            ["reading_skimming_scanning"],
            exam=exam,
            resource_query="IELTS Reading True False Not Given strategy practice",
        ),
        TaskNode(
            "reading_timed_section",
            "Timed reading section practice",
            "reading",
            60,
            82,
            4,
            ["reading_matching_headings", "reading_tfn"],
            exam=exam,
            resource_query="IELTS Reading timed section practice answer analysis",
        ),
        TaskNode(
            "listening_section1",
            "Section 1 daily conversation",
            "listening",
            35,
            48,
            2,
            exam=exam,
            resource_query="IELTS Listening Section 1 daily conversation practice",
        ),
        TaskNode(
            "listening_map_labeling",
            "Map labeling",
            "listening",
            40,
            58,
            3,
            ["listening_section1"],
            exam=exam,
            resource_query="IELTS Listening map labeling practice strategy",
        ),
        TaskNode(
            "listening_multiple_choice",
            "Multiple choice listening",
            "listening",
            45,
            62,
            3,
            ["listening_section1"],
            exam=exam,
            resource_query="IELTS Listening multiple choice distractor practice",
        ),
        TaskNode(
            "listening_full_mock",
            "Full listening mock practice",
            "listening",
            60,
            80,
            4,
            ["listening_map_labeling", "listening_multiple_choice"],
            exam=exam,
            resource_query="IELTS full listening mock test with transcript analysis",
        ),
        TaskNode(
            "speaking_part1_fluency",
            "Part 1 fluency drills",
            "speaking",
            35,
            50,
            2,
            exam=exam,
            resource_query="IELTS Speaking Part 1 fluency drills common questions",
        ),
        TaskNode(
            "speaking_part2_cue_card",
            "Part 2 cue card structure",
            "speaking",
            45,
            66,
            3,
            ["speaking_part1_fluency"],
            exam=exam,
            resource_query="IELTS Speaking Part 2 cue card structure practice",
        ),
        TaskNode(
            "speaking_part3_discussion",
            "Part 3 abstract discussion",
            "speaking",
            50,
            70,
            4,
            ["speaking_part2_cue_card", "foundation_academic_vocab"],
            exam=exam,
            resource_query="IELTS Speaking Part 3 abstract discussion answers feedback",
        ),
        TaskNode(
            "speaking_mock_review",
            "Mock speaking response review",
            "speaking",
            55,
            78,
            4,
            ["speaking_part3_discussion"],
            exam=exam,
            resource_query="IELTS Speaking mock response review fluency coherence vocabulary pronunciation",
        ),
    ]


def build_toefl_task_graph() -> list[TaskNode]:
    exam = "TOEFL"
    return [
        TaskNode("toefl_foundation_note_taking", "Academic note-taking foundation", "foundation", 45, 52, 2, exam=exam),
        TaskNode("toefl_reading_inference", "Reading inference questions", "reading", 45, 64, 3, exam=exam),
        TaskNode("toefl_reading_timed_set", "Timed reading question set", "reading", 60, 82, 4, ["toefl_reading_inference"], exam=exam),
        TaskNode("toefl_listening_lecture", "Lecture listening structure", "listening", 50, 68, 3, ["toefl_foundation_note_taking"], exam=exam),
        TaskNode("toefl_speaking_independent", "Independent speaking response", "speaking", 45, 66, 3, exam=exam),
        TaskNode(
            "toefl_speaking_integrated",
            "Integrated speaking synthesis",
            "speaking",
            55,
            76,
            4,
            ["toefl_foundation_note_taking", "toefl_listening_lecture"],
            exam=exam,
        ),
        TaskNode("toefl_writing_independent", "Independent writing structure", "writing", 55, 72, 3, exam=exam),
        TaskNode(
            "toefl_writing_integrated",
            "Integrated writing from reading and lecture",
            "writing",
            60,
            84,
            4,
            ["toefl_foundation_note_taking", "toefl_listening_lecture"],
            exam=exam,
        ),
    ]


def build_all_sample_tasks() -> list[TaskNode]:
    return [*build_ielts_task_graph(), *build_toefl_task_graph()]
